name: Unbanked.red
favicon: null
layout_spectrum: 0.8664277994539589
typography_spectrum: 0.18840670748613775
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8796900226734579
  lightness: 0.5264583169482648
  saturation: 0.9470164233352989
  rhythmicContrast: 0.791544487234205
purpose: []
